export const ORDER_INTAKE_QUEUE = {
  NAME: 'ORDERS_INTAKE_QUEUE',
  JOBS: {
    ENQUEUE_ORDER: 'ORDERS_INTAKE_JOB',
  },
  DEFAULT_TIMEOUT_MS: 60_000,
} as const;

export const ORDER_PREPARE_QUEUE = {
  NAME: 'ORDERS_PREPARE_QUEUE',
  JOBS: {
    PREPARE_ORDER: 'ORDERS_PREPARE_ORDER_JOB',
  },
  DEFAULT_TIMEOUT_MS: 180_000,
} as const;

export const MOTOR_MOVEMENTS_QUEUE = {
  NAME: 'MOTOR_MOVEMENTS_QUEUE',
  JOBS: {
    COMMAND: 'MOTOR_COMMAND_JOB',
  },
  DEFAULT_TIMEOUT_MS: 10_000,
} as const;
