export const INTAKE_ORDERS_QUEUE = 'ORDERS_INTAKE_QUEUE';
export const PREPARE_ORDERS_QUEUE = 'ORDERS_PREPARE_QUEUE';
export const MOTOR_MOVEMENTS_QUEUE = 'MOTOR_MOVEMENTS_QUEUE';

export const PREPARE_ORDER_JOB_NAME = 'ORDERS_PREPARE_ORDER_JOB';
export const MOTOR_COMMAND_JOB_NAME = 'MOTOR_COMMAND_JOB';
