export const HARDWARE_USB_TRANSPORT = 'HARDWARE_USB_TRANSPORT';

export const MOTOR_COMMAND_KEYS = {
  MOVE_Y_TO_HOPPER: 'MOVE_Y_TO_HOPPER',
  MOVE_X_TO_CENTER: 'MOVE_X_TO_CENTER',
  MOVE_X_TO_LEFT: 'MOVE_X_TO_LEFT',
  MOVE_X_TO_RIGHT: 'MOVE_X_TO_RIGHT',
  MOVE_Z_LEFT_ROTATION: 'MOVE_Z_LEFT_ROTATION',
  MOVE_Z_RIGHT_ROTATION: 'MOVE_Z_RIGHT_ROTATION',
  MOVE_A_OPEN: 'MOVE_A_OPEN',
  MOVE_A_CLOSE: 'MOVE_A_CLOSE',
  MOVE_Y_HOME: 'MOVE_Y_HOME',
  MOVE_X_HOME: 'MOVE_X_HOME',
  MOVE_A_HOME: 'MOVE_A_HOME',
} as const;

export type MotorCommandKey =
  (typeof MOTOR_COMMAND_KEYS)[keyof typeof MOTOR_COMMAND_KEYS];

export const AXIS_EVENT_KEYS = {
  Y_AXIS_MOVE_COMPLETED: 'Y_AXIS_MOVE_COMPLETED',
  X_AXIS_MOVE_COMPLETED: 'X_AXIS_MOVE_COMPLETED',
  A_AXIS_MOVE_COMPLETED: 'A_AXIS_MOVE_COMPLETED',
  Z_AXIS_MOVE_COMPLETED: 'Z_AXIS_MOVE_COMPLETED',
  Y_AXIS_HOME_COMPLETED: 'Y_AXIS_HOME_COMPLETED',
  X_AXIS_HOME_COMPLETED: 'X_AXIS_HOME_COMPLETED',
  A_AXIS_HOME_COMPLETED: 'A_AXIS_HOME_COMPLETED',
} as const;

export type AxisEventKey =
  (typeof AXIS_EVENT_KEYS)[keyof typeof AXIS_EVENT_KEYS];

export const SENSOR_EVENT_KEYS = {
  Y_AXIS_SENSITIVE: 'Y_AXIS_SENSITIVE',
  X_AXIS_SENSITIVE: 'X_AXIS_SENSITIVE',
} as const;

export type SensorEventKey =
  (typeof SENSOR_EVENT_KEYS)[keyof typeof SENSOR_EVENT_KEYS];
